version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    ports:
      - "8080:80"
    volumes:
      - ./mlruns:/app/mlruns #mount local mlruns to docker
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns 

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi