FROM python:3.9

WORKDIR /app

COPY . /app

RUN pip install fastapi uvicorn scikit-learn xgboost pydantic pandas pyyaml

EXPOSE 80

#app.app:app - folder.file:object
CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]