FROM python:3.9

WORKDIR /deployment

COPY . /deployment/

RUN pip install fastapi uvicorn scikit-learn xgboost pydantic pandas pyyaml mlflow

EXPOSE 80

#app.app:app - folder.file:object
CMD ["uvicorn", "deployment.app:app", "--host", "0.0.0.0", "--port", "80"]