FROM python:3.9

WORKDIR /app

COPY ./deployment /app/deployment
COPY ./configs /app/configs
COPY ./ml /app/ml
COPY ./mlruns /app/mlruns

RUN pip install fastapi uvicorn scikit-learn xgboost pydantic pandas pyyaml mlflow

EXPOSE 80

#app.app:app - folder.file:object
CMD ["uvicorn", "deployment.app:app", "--host", "0.0.0.0", "--port", "80"]