FROM python:3.9

WORKDIR /streamlit_app

COPY ./deployment ./streamlit_app

RUN pip install streamlit requests pydantic

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]