stages:
  preprocess:
    cmd: python src/data_preprocessing/trades_processing.py
    deps:
    - data/raw
    - src/data_preprocessing/trades_processing.py
    outs:
    - data/processed
  plot:
    cmd: jupyter notebook notebooks/processed_data_distribution.ipynb
    deps:
      - data/processed
    outs:
      - notebooks/plot_results.ipynb