name: deploy_assignment
dependencies:
  - python=3.9
  - numpy
  - pandas
  - seaborn
  - mlflow
  - streamlit
  - fastapi
  - uvicorn
  - scikit-learn
  - scipy
  - streamlit
  - requests
  - pickle
  - pip
  - pip:
      - "fastapi[standard]"
      - dvc
      - dvc[gdrive]
      - apache-airflow
      - hydra-core